In [ ]:
import numpy as np
arr = np.arange(1, 10, 2)
print(arr)

In [7]:
import numpy as np
array = np.ones((3, 4))
print(array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
import numpy as np

division_array = np.linspace(0, 1, 10)

print(division_array)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [1]:
import numpy as np

A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]])

print(A.shape)

value_19 = A[3, 3]
print("19 값:", value_19)

slice1 = A[:2, :2]
print(slice1)

slice2 = A[3:, 3:]
print(slice2)

rows_01 = A[:2, :]
print(rows_01)

cols_last_two = A[:, -2:]
print(cols_last_two)


(5, 5)
19 값: 19
[[1, 2], [6, 7]] 슬라이싱 결과:
[[1 2]
 [6 7]]
[[19, 20], [24, 25]] 슬라이싱 결과:
[[19 20]
 [24 25]]
0축의 첫 번째 행과 두 번째 행:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1축의 마지막 열과 마지막 직전 열:
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [ ]:
import numpy as np
array = np.array([[[1,2,3,4],
                   [5,6,7,8],
                   9,10,11,12]],
                 [[13,14,15,16],
                  [17,18,19,20],
                 [21,22,23,24]]
                 [[25,26,27,28],
                  [29,30,31,32],
                  [33,34,35,36]]])

In [6]:
import numpy as np

arr = np.arange(1, 37)

matrix_3d = arr.reshape(3, 4, -1)

print(matrix_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


모르겠습니다..